### PR TITLE
Fix LengthHiding middleware for Rails 3.0

### PR DESCRIPTION
**Pull request by ehlertij**
This resolves the middleware issue I brought up in https://github.com/meldium/breach-mitigation-rails/pull/3

### CODE REVIEW

**Comment by bradleybuda** [comment]
So we're not tied to a particular Rails version, how about something like this (I haven't tested yet):

``` ruby
middleware = app.config.middleware
target = "Rack::ETag"
if middleware.any? { |m| m.name == target }
  middleware.insert_before target, "BreachMitigation::LengthHiding"
else
  middleware.use "BreachMitigation::LengthHiding"
end
```

**Comment by ehlertij** [comment]
I tried doing something similar to that too, since it'd definitely be cleaner. Unfortunately, the middleware object is a `Rails::Configuration::MiddlewareStackProxy` object and only has these methods available `[:delete, :insert, :insert_after, :insert_before, :merge_into, :swap, :use]`.

I also tried rescuing from the RuntimeError (also gross), but it doesn't get thrown until later.

This was the only other way I could think to handle the issue somewhat gracefully.

**Comment by bradleybuda** [comment]
Cool; thanks for the patch!

**Comment by ehlertij** [comment]
No problem, thanks for this gem!

**Pull request merged**
