### PR TITLE
Insert middleware before Rack::ETag

### PR DESCRIPTION
**Pull request by Bertg**
> The length-hiding middleware adds random text (in the form of an HTML comment) to every page you serve. This can break HTTP caching / ETags for public pages since they are no longer identical on each request.

This can easily be resolved by letting `BreachMitigation::LengthHiding` do it's work after `Rack::ETag`.

I didn't test his, but seems fairly obvious.

### CODE REVIEW

**Comment by bradleybuda** [comment]
Works for me - thanks for the contribution!

**Comment by Bertg** [comment]
I forgot to add a readme fix, maybe you can still do that? ;)

**Comment by ehlertij** [comment]
This change causes an exception if the `Rack::ETags` middleware is not included.

```
.../gems/actionpack-3.0.20/lib/action_dispatch/middleware/stack.rb:86:in `assert_index': No such middleware to insert before: "Rack::ETag" (RuntimeError)
```

**Comment by Bertg** [comment]
True, however that means you are modifying the rails default stack. 
So I think it's then up to you to correct it.

**Comment by ehlertij** [comment]
`Rack::ETag` wasn't added by default until Rails 3.1, so it breaks Rails 3.0 apps. https://github.com/rails/rails/blob/7ead1d81431b2c2c0366347b7bfdf9a329b6f934/guides/source/3_1_release_notes.md

**Comment by Bertg** [comment]
Ok, I didn't know that. I could provide a fix.
However, don't you think that rails <3.1 apps have bigger security issues to think about?

**Pull request merged**
