### PR TITLE
Speedup length hiding comment generation

### PR DESCRIPTION
**Pull request by denzel-morris**
I believe this to be a faster option, and ran a simple benchmark to test as such:

``` ruby
require 'benchmark'
ALPHABET = ('a'..'z').to_a
N = 1000000
Benchmark.bmbm do |x|
  x.report('concatenation') do
    junk = ''
    N.times { junk << ALPHABET.sample }
  end

  x.report('join') do
    junk = ALPHABET.sample(N).join
  end
end

# Rehearsal -------------------------------------------------
# concatenation   0.420000   0.000000   0.420000 (  0.418906)
# join            0.000000   0.000000   0.000000 (  0.000019)
# ---------------------------------------- total: 0.420000sec
#
#                     user     system      total        real
# concatenation   0.410000   0.000000   0.410000 (  0.418474)
# join            0.000000   0.000000   0.000000 (  0.000018)
```

### CODE REVIEW

**Comment by bradleybuda** [comment]
Didn't know sample took an integer argument - awesome, thanks!

**Comment by denzel-morris** [comment]
No problem, thanks for helping out the community with this gem.

**Comment by vitaliel** [comment]
The problem with Array#sample is that will give you a string with maximum length = array size.

```
1.9.3p194 :018 > ('a'..'z').to_a.sample(2048).join.length
 => 26 
```

**Comment by denzel-morris** [comment]
Indeed you're right @vitaliel! I apologize for the shortcoming.

There's a couple ways to solve this: 1) we could continue to sample from the alphabet and speed this up at the cost of some memory, or 2) we could simply sample from the set of hexadecimal characters with a secure PRNG.

Option 1

``` ruby
require 'benchmark'
ALPHABET = ('a'..'z').to_a
N = 1000000
Benchmark.bmbm do |x|
  x.report('concatenation') do
    junk = ''
    N.times { junk << ALPHABET.sample }
  end

  x.report('join') do
    junk = (ALPHABET*(N/26.0).ceil).sample(N).join
  end
end
#  Rehearsal -------------------------------------------------
#  concatenation   0.420000   0.000000   0.420000 (  0.423192)
#  join            0.190000   0.010000   0.200000 (  0.195562)
#  ---------------------------------------- total: 0.620000sec
#
#                      user     system      total        real
#  concatenation   0.410000   0.000000   0.410000 (  0.414539)
#  join            0.200000   0.000000   0.200000 (  0.196314)
```

Option 2

``` ruby
require 'securerandom'
require 'benchmark'
ALPHABET = ('a'..'z').to_a
N = 1000000
Benchmark.bmbm do |x|
  x.report('concatenation') do
    junk = ''
    N.times { junk << ALPHABET.sample }
  end

  x.report('random hex') do
    junk = SecureRandom.hex(N)
  end
end
#  Rehearsal -------------------------------------------------
#  concatenation   0.410000   0.000000   0.410000 (  0.418563)
#  random hex      0.110000   0.000000   0.110000 (  0.112426)
#  ---------------------------------------- total: 0.520000sec
#
#                     user     system      total        real
#  concatenation   0.420000   0.000000   0.420000 (  0.415808)
#  random hex      0.110000   0.000000   0.110000 (  0.112795)
```

I guess it just depends on what @bradleybuda wants to do.

**Comment by vitaliel** [comment]
Another option:

```
junk = 'z' * rand_len #reserve RAM
rand_len.times {|i| junk[i] = ALPHABET[rand(ALPHABET.size)]}
```

**Pull request merged**
